language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
before_deploy:
- ./gradlew build
deploy:
- provider: script
  script: "curl --ftp-create-dirs -T app/build/outputs/apk/app-release-unsigned.apk -u \"$FTP_CREDENTIALS\" ftp://ftp.reederhome.net/turbo-spork-latest.apk"
  skip_cleanup: true
  on:
    repo: fictional-pancake/turbo-spork-android
